version: "3.9"
services:
  quality-api:
    build: .
    image: auto-ingest-quality-api:latest
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-livelongandprosper}
      NEO4J_DB: ${NEO4J_DB:-neo4j}
      MEDIA_BASE: ${MEDIA_BASE:-/data/audio}
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:8000 quality_api.wsgi:app
